const test=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.join(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");

test("recitation engine loads before the app",()=>{const html=read("dist/index.html"),core=html.indexOf("recitation-core.js"),app=html.indexOf("app.js?v=29");assert.ok(core>0&&app>core);});
test("every JavaScript element lookup exists in the page",()=>{const html=read("dist/index.html"),app=read("dist/app.js"),ids=new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]));for(const match of app.matchAll(/\$\("#([^"]+)"\)/g))assert.ok(ids.has(match[1]),match[1]);});
test("the page has no duplicate element IDs",()=>{const ids=[...read("dist/index.html").matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]),unique=new Set(ids);assert.equal(unique.size,ids.length);});
test("all versioned local styles and scripts exist",()=>{const html=read("dist/index.html");for(const match of html.matchAll(/(?:href|src)="\.\/([^"?]+)(?:\?[^\"]*)?"/g))assert.ok(fs.existsSync(path.join(root,"dist",match[1])),match[1]);});
test("offline cache includes every local app asset",()=>{const sw=read("dist/service-worker.js");for(const asset of ["index.html","styles.css?v=30","recitation-core.js?v=29","app.js?v=29","favicon.svg","manifest.webmanifest"])assert.ok(sw.includes(asset),asset);});
test("startup screen uses AyahFlow branding and waits for app readiness",()=>{const html=read("dist/index.html"),app=read("dist/app.js"),css=read("dist/styles.css");assert.match(html,/id="startupScreen" role="status"/);assert.match(html,/startup-wordmark">Ayah<span>Flow/);assert.match(app,/quranReady=loadQuran\(\)/);assert.match(app,/document\.fonts\?\.ready/);assert.match(app,/Promise\.race/);assert.match(app,/dismissStartup/);assert.match(css,/\.startup-screen\.is-leaving/);});
test("Easy Study keeps translations attributed and commentary separate",()=>{const html=read("dist/index.html"),app=read("dist/app.js");assert.match(html,/value="study\.easy"/);for(const edition of ["en.itani","en.sahih","en.pickthall","en.yusufali","en.asad","en.hilali"])assert.ok(app.includes(edition),edition);assert.match(app,/each published translation separate/);assert.match(app,/not a replacement for the Arabic Quran/);assert.match(html,/Translations and commentary remain separate and attributed/);});
test("contextual English uses attributed bracketed clarification",()=>{const app=read("dist/app.js"),css=read("dist/styles.css"),html=read("dist/index.html");assert.match(app,/identifier==="study\.easy"\?"en\.sahih"/);assert.match(app,/function formatTranslation/);assert.match(app,/translator-supplied clarifications/);assert.match(css,/\.translation-clarification/);assert.match(html,/Contextual English · brackets \+ context/);});
test("ayah Study action opens the comparison and context view",()=>{const app=read("dist/app.js");assert.match(app,/data-action="study"/);assert.match(app,/action\?\.dataset\.action==="study"\)openStudy/);assert.doesNotMatch(app,/openTafsir/);});
test("Quran reader is not an overactive live region",()=>{const html=read("dist/index.html");assert.match(html,/id="verses" aria-label="Quran reader"/);assert.doesNotMatch(html,/id="verses" aria-live/);});
test("both microphone controls expose pressed state",()=>{const html=read("dist/index.html");assert.equal((html.match(/aria-pressed="false"/g)||[]).length>=2,true);});
test("mobile reader reserves room for the floating microphone",()=>assert.match(read("dist/styles.css"),/padding: 1\.25rem \.85rem calc\(4\.5rem \+ env\(safe-area-inset-bottom\)\)/));
test("keyboard focus remains visible",()=>assert.match(read("dist/styles.css"),/button:focus-visible/));
test("unsupported guessed tafkhim coloring is absent",()=>{const app=read("dist/app.js"),css=read("dist/styles.css");assert.doesNotMatch(app,/ALWAYS_HEAVY_LETTERS/);assert.doesNotMatch(css,/tajweed-tafkhim/);});
test("known malformed Quran glyphs are normalized",()=>{const app=read("dist/app.js");assert.match(app,/\\u066E\/gu,"\\u0649"/);assert.match(app,/\\u0672\/gu,"\\u0670"/);});
test("surah headings do not duplicate the leading Bismillah",()=>assert.match(read("dist/app.js"),/stripLeadingBismillah/));
test("recognizer evaluates multiple alternatives",()=>{const app=read("dist/app.js");assert.match(app,/maxAlternatives=5/);assert.match(app,/chooseAlternative/);});
test("live word tracking uses constant-time verse lookup",()=>{const app=read("dist/app.js");assert.match(app,/verseLookup\.get/);assert.doesNotMatch(app,/function verseEntry\([^)]*\)\{return state\.flatVerses\.find/);});
test("hidden apps pause microphone reconnection",()=>{const app=read("dist/app.js");assert.match(app,/visibilitychange/);assert.match(app,/recognitionPausedForVisibility/);});
test("following can catch up only inside the same surah",()=>assert.match(read("dist/app.js"),/afterNext\.surah===current\.surah/));
test("manual reading temporarily pauses automatic following scroll",()=>assert.match(read("dist/app.js"),/followScrollPausedUntil=Date\.now\(\)\+3500/));
test("reduced-motion users do not receive forced smooth following",()=>{assert.match(read("dist/app.js"),/prefers-reduced-motion: reduce/);assert.match(read("dist/styles.css"),/@media \(prefers-reduced-motion: reduce\)/);});
